server:
  port: 9004

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/kart
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create

  